### PR TITLE
For new projects, prompt to get geometry from (a) database (b) file

### PR DESCRIPTION
**Pull request by pjknowles**

### CODE REVIEW

**Comment by pjknowles** [comment]
@hjwerner and @klauspdoll I wonder what you think of this. For a new project, this will immediately pop up a box to ask to import geometry from pubchem/chemspider. If that is cancelled (or otherwise leads to nothing), it will ask whether you want to import a geometry file.  If you don't want to do anything like this, it goes away by hitting escape twice, but it seems to me that this will be more useful for most projects than relying on drawing the molecule from scratch.

One could discuss whether it's more helpful to prompt for file import first, rather than second, and that discussion should consider every kind of user and use.

**Comment by hjwerner** [comment]
Dear Peter,

first of all, I still get the network error can cannot load a geometry from the Web. Second, at least for me it is much more likely (>99%) that I use a geometry that I have stored earlier than taking one from the Web. So my preferred default would be to ask for a geometry file (and remember the previous directory used for this purpose - which I think you have already implemented), and only if there is none one can try the Web.

Best wishes
Joachim

**Comment by pjknowles** [comment]
> first of all, I still get the network error can cannot load a geometry from the Web. Second, at least for me it is much more likely (>99%) that I use a geometry that I have stored earlier than taking one from the Web. So my preferred default would be to ask for a geometry file (and remember the previous directory used for this purpose - which I think you have already implemented), and only if there is none one can try the Web.

Yes, I think that's a good point. The network errors are frustrating and difficult to understand; we will fix them eventually but it might not be soon.  As things stand, it's not possible to make a binary for which pubchem search will work, so I will switch the order round.

**Comment by pjknowles** [comment]
It seems that the network problems are all about pubchem, and that searching ChemSpider instead seems to work. I have made pubchem off by default, until this can be understood. This, together with file import first, can be tested with https://github.com/molpro/iMolpro/releases/tag/test-new-prompt . For ChemSpider, you can get the necessary key from https://developer.rsc.org/get-started .

The main thing to decide is whether we want these invitations to import geometry, which can be dismissed with a coupled of taps on the escape key, or whether the geometry is just left unresolved, for a new project.

**Comment by hjwerner** [comment]
I think it is good to be prompted for the geometry. Without it, one can’t do a calculation anyway. But one should be able to skip this step, since one might want to enter the geometry manually (e.g. a zmat input).

**Comment by pjknowles** [comment]
OK, then let's go for it. If you don't want to import a geometry, it's as simple as hitting the escape key twice. I'll put something in the documentation.

**Pull request merged**
