### PR TITLE
Tidy

### PR DESCRIPTION
**Pull request by klauspdoll**

### CODE REVIEW

**Comment by klauspdoll** [comment]
I just want to tidy a bit before going back to the df- u etc stuff in https://github.com/molpro/iMolpro/pull/75

**Review by pjknowles — APPROVED** [review]
Of course it's fine. I'd recommend normally basing branches to merge on the latest, or near-latest, tip of master so that the history is not cluttered by merge loops, or you can just rebase when the PR is merged.

**Comment by klauspdoll** [comment]
Yes, that's what I don't quite get. I think I did "Squash and merge", "Rebase and merge" in the PRs before, but still it tells me that there are 11 commits.

**Comment by pjknowles** [comment]
You can just start the branch from an up to date master, or, before you push to your fork for the first time, `git rebase origin/master`. Or even do it later, and force-push to your fork.

**Pull request merged**
