### PR TITLE
remember directories

### PR DESCRIPTION
**Pull request by pjknowles**
- remember and use latest directories for import and export
- remember and use latest directories for projects

### CODE REVIEW

**Comment by pjknowles** [comment]
Fix #34 . There are three global settings, `project_directory`, `import_directory`, `export_directory`. One could consider splitting `import_directory` into different types (geometry, input, other) but maybe this leads to behaviour that is less easy to understand.

**Comment by hjwerner** [comment]
For me separating the geometry directory would be helpful, since I have stored many xyz files in a particular directory. This is not the same from which typically inputs or other stuff is imported. So I would appreciate splitting "import directory" into "import directory" and "geometry directory".

**Comment by pjknowles** [comment]
> For me separating the geometry directory would be helpful, since I have stored many xyz files in a particular directory. This is not the same from which typically inputs or other stuff is imported. So I would appreciate splitting "import directory" into "import directory" and "geometry directory".

Done. Anything else, or OK to merge and test?

**Comment by hjwerner** [comment]
I haven’t looked and tested any more. Please push, and when anything else comes up it can be fixed later.
Joachim

**Pull request merged**
