### PR TITLE
begin with default basis set (do not merge)

### PR DESCRIPTION
**Pull request by klauspdoll**

### CODE REVIEW

**Comment by klauspdoll** [comment]
This needs tidying, I'll let you know when it is ready to be considered for a merge.

**Comment by klauspdoll** [comment]
There are yet bugs:

1 ) when changing the basis set in freehand mode, then the hamiltonian would have to be properly set first to have the correct pulldown to choose the basis set typed in in freehand mode. Otherwise if "All electron" is chosen in the Hamilonian pulldown and a PP basis set typed in, then it is not  found in the pulldown which gives problems

2 ) problems with "Select basis set..." - needs to be sorted out; do we need that at all ?

**Review by pjknowles — CHANGES_REQUESTED** [review]
Compared to master, I see the following

- A new project starts with no basis set in the input, and opens the `freehand` instead of `guided` pane.
- On subsequently selecting from the basis quality combo, the program segfaults. Unfortunately this is not trapped by the debugger
- On restarting and reopening the project, you can select from the quality combo, but the consequence is that you end up in the freehand mode only, with the unhelpful `basis={default=Select basis set...}` in the input.

**Review by pjknowles — CHANGES_REQUESTED** [review]
Furthermore, this input:
```
geometry=ChemSpider-14122.xyz
basis={default=cc-pvdz}
rhf

put,molden,default-basis3.molden
```
does not any more load guided mode, because the basis set does not make it into the input specification.

**Comment by klauspdoll** [comment]
I have now pushed all changes I did to this branch, but please do not merge it.

I will continue with looking into the new basis stuff in parse_basis

**Review by pjknowles — COMMENTED** [review]
I think everything that is here is superseded by #148 and that this PR should be abandoned. @klauspdoll  OK?

**Comment by klauspdoll** [comment]
Yes, this is redundant now and I close this PR.

**Pull request closed without merging**
