### PR TITLE
Strengthen documentation of ssh to help find a compliant ssh configuration for remote backends.

### PR DESCRIPTION
**Pull request by pjknowles**

### CODE REVIEW

**Comment by hjwerner** [comment]
where is the documentation?

**Comment by pjknowles** [comment]
> where is the documentation?

It shows in iMolpro from menu Help/backends but of course you won't see these changes there yet.

**Comment by hjwerner** [comment]
That’s where I looked.

**Comment by pjknowles** [comment]
I guess I'll just merge this as it's not controversial.

**Pull request merged**
