### PR TITLE
Prevent overwriting existing project when asking for new project.

### LINKED ISSUE #129: Project / New does not check if the project already exists
`Project / New` does not check if the project already exists. This is somewhat unexpected, as I would think
it would disallow this.

It then effectively does the same as File/Open; File/Open can open a project second time (which is okay).

Example:

start iMolpro

make a new project `Projekt / New `  called bla10

do again `Project / New` and call the project also bla10

a second GUI window opens, the same project bla10 is opened a second time. Nothing bad happens, but one would expect a new project being created, instead possibly an old project being reopened.

### PR DESCRIPTION
**Pull request by pjknowles**
Fixes #129

### CODE REVIEW

**Review by klauspdoll — COMMENTED** [review]
It does not yet trap the case

Project/New

**Comment by pjknowles** [comment]
> It does not yet trap the case
> 
> Project/New

Can you be more specific about what you see that doesn't work?

**Comment by klauspdoll** [comment]
> > It does not yet trap the case
> > Project/New
> 
> Can you be more specific about what you see that doesn't work?

I have version 733a169f
I create a project bla5 and open it.
Now I do Projects/New and type bla5 . It opens a second window.

**Comment by pjknowles** [comment]
Perhaps with https://github.com/molpro/iMolpro/pull/132/commits/b80e1527cfb1512eec1db75640b7df972e2e489e it is better - no dialog popped in the file chooser when existing file name is specified.

**Comment by klauspdoll** [comment]
> Perhaps with [b80e152](https://github.com/molpro/iMolpro/commit/b80e1527cfb1512eec1db75640b7df972e2e489e) it is better - no dialog popped in the file chooser when existing file name is specified.

No, it is the same I am afraid.

**Comment by pjknowles** [comment]
> I create a project bla5 and open it.
> Now I do Projects/New and type bla5 . It opens a second window.

I see. So if the existing project is open, the check does not work, but if it's closed, it does. I will look.

**Comment by pjknowles** [comment]
> > I create a project bla5 and open it.
> > Now I do Projects/New and type bla5 . It opens a second window.
> 
> I see. So if the existing project is open, the check does not work, but if it's closed, it does. I will look.

So it works if new is done from the chooser, but not from a `ProjectWindow`.

**Review by klauspdoll — APPROVED** [review]
Works now, traps all cases.

**Pull request merged**
