### PR TITLE
Option in guided mode to save orbitals to a molden file at the end of the job.

### PR DESCRIPTION
**Pull request by pjknowles**
One day this might be a molpro xml file when jmol can support that.
The option is on by default, but might want it off for a very large molecule.

### CODE REVIEW

**Review by klauspdoll — COMMENTED** [review]
It is okay, apart from when you have run a calculation:

set up new project bla5
```
geometry={he}
basis={default=cc-pVTZ-PP}
rhf

put,molden,bla5.molden

```
run, then un-click "Generate orbitals..."
then click "Generate orbitals...", you have:

```
geometry={
he
}
basis={default=cc-pVTZ-PP}
rhf

put,molden,bla5.molden
put,molden,bla5_1.molden

```
should it remove `put,molden,bla5.molden` ? or leave it to the user to remove it via the freehand mode ?

**Comment by pjknowles** [comment]
Thanks, I did it the wrong way and will fix.

**Comment by pjknowles** [comment]
Hopefully now fixed - always the project name is used to construct the molden file name

**Review by klauspdoll — APPROVED** [review]
Yes, looks good.

**Comment by klauspdoll** [comment]
The switch freehand -> guided may yet  be incorrect: when I delete `put,molden,bla5.molden`
then the box "Generate orbitals ..." remains ticked; similar when I insert the command, the box does not get ticked.

**Comment by pjknowles** [comment]
Thanks, I've pushed the fix f55dc32 into master.

**Comment by klauspdoll** [comment]
Yes, now it works.

**Pull request merged**
