### PR TITLE
Fixes #64

### LINKED ISSUE #64: freehand mode: cursor jumps to upper left corner when typing
in freehand mode, starting from this input:

```
geometry=dummy.xyz
basis={default=cc-pVTZ-PP}
rhf
```

I want to append a line with

`ccsd`

While typing, the cursor often jumps to the upper left part of the window, which is inconvenient; e.g. usually after having typed the first "c" of ccsd, the cursor jumps to the upper left

### PR DESCRIPTION
**Pull request by pjknowles**

### CODE REVIEW

**Comment by klauspdoll** [comment]
I am afraid it still fails. Just open a new project, and slowly type 

ccsd

at the end - after the first c , it jumps to the upper left.

**Review by klauspdoll — CHANGES_REQUESTED** [review]
I am afraid it still fails:  Just open a new project, and slowly type

ccsd

at the end - after the first c , it jumps to the upper left.

**Comment by pjknowles** [comment]
Maybe better now?

**Review by klauspdoll — COMMENTED** [review]
I am afraid it sill does not  work.
And I have seen that some print statements were inserted, but I cannot see anything  printed to the terminal.

steps to reproduce:

1) git log
commit fe9b86c87ae3977bfa74182ce395020afa2a5689 (HEAD -> fix_64, upstream/fix_64)

2) python iMolpro.py

3) create a new project: bla.molpro

4) go to end of input field, line below "rhf"

5) slowly try to type "ccsd" - after having typed the first "c", the cursor jumps to the upper left corner, before "geometry=bla.xyz" ; nothing printed to the terminal

**Comment by pjknowles** [comment]
There must be a remaining refresh of the input that should not be happening when the input tab is in foreground. Difficult to reproduce as the behaviour depends on a race between threads. But I will find and fix.

**Comment by pjknowles** [comment]
Problem understood. On typing on the last line, `EditFile.sync()` gets the idea that it needs to add a newline at the end of the file, and this causes the cursor to get lost.

**Review by klauspdoll — APPROVED** [review]
Yes, now it works, thank you.

**Comment by pjknowles** [comment]
> Yes, now it works, thank you.

Thanks .. so can you now please complete the review with 'approve'?

**Review by klauspdoll — APPROVED** [review]
I had already approved with the button on the upper right, but this seems not sufficient. Try to approve again.

**Review by klauspdoll — APPROVED** [review]
and approve again ...

**Comment by pjknowles** [comment]
> and approve again ...

Not sure why this doesn't do anything, but I can force merge easily.

**Review by klauspdoll — APPROVED** [review]
I am not sure, it says:

At least 1 approving review is required by reviewers with write access

Do you have to approve is yourself, Peter?

**Comment by pjknowles** [comment]
It's all confusing. @klauspdoll I have increased your access to 'write' which should mean that you can now approve PRs.

**Pull request merged**
