### PR TITLE
try to sync my master with molpro/iMolpro

### PR DESCRIPTION
**Pull request by klauspdoll**

### CODE REVIEW

**Review by pjknowles — CHANGES_REQUESTED** [review]
There is simply no change in this PR, and it should just be dropped.

**Comment by pjknowles** [comment]
This is just git basics. Maybe something like
```
git checkout master
git reset --hard origin/master
git push --force
```
depending on what you have called your remotes locally.

**Comment by klauspdoll** [comment]
yes, I know, but github keeps telling that my master is ahead of upstream's master. I hope that this may synchronise things. Otherwise I may have to freshly fork.

**Comment by pjknowles** [comment]
> yes, I know, but github keeps telling that my master is ahead of upstream's master. I hope that this may synchronise things. Otherwise I may have to freshly fork.

But the merge will have absolutely no effect, other than maybe putting unnecessary loops in the history. The problem, if there is one, is the state of your fork, and/or local copy. If you want to get it right, always start your new branches from the tip of master from molpro/iMolpro . If you haven't done that, repair is easy with a bit of `--force`.

**Comment by pjknowles** [comment]
It can sometimes help to reduce the confusion level to never use the master branch on your fork - neither push nor pull - but to checkout the official master instead

**Comment by klauspdoll** [comment]
Thank you, I hope it is fixed now.

I used the syntax as you give above, with (upstream instead of origin):

```
git checkout master
git reset --hard upstream/master
git push --force

```
and my master is up to date with molpro/iMolpro:master

**Pull request closed without merging**
