### PR TITLE
Terminal and Explorer launchers

### PR DESCRIPTION
**Pull request by pjknowles**
Addresses #43

### CODE REVIEW

**Comment by pjknowles** [comment]
@ajmay81 could you please help with the linux side of this? The idea is that the program launches a file explorer window, or launches a terminal window, both with their working directory prescribed. I'm aware that in both cases on linux there are alternatives, which should be coded up as far as possible; is there a concept of a preferred terminal app or preferred explorer?

**Comment by pjknowles** [comment]
fixes #43

**Comment by ajmay81** [comment]
Can't one use [QFileDialog](https://doc.qt.io/qt-6/qfiledialog.html) to open a file explorer in a portable way?

**Comment by ajmay81** [comment]
And according to [this](https://stackoverflow.com/questions/36177616/preventing-file-actions-in-qfiledialog-such-as-copying-viewing-deleting-etc) all file actions can be done by QFileDialog, so there is no need then to launch a terminal.

**Comment by pjknowles** [comment]
So this becomes a bit of a discussion item. The original request was to implement delete and rename, and this is certainly easily done portably with a Qt dialog. But the idea for terminal and file explorer came because sometimes you might prefer to do it your own way. This is what you find in IDEs and also in photo catalogues. Maybe terminal is useful still, but the file explorer could be replaced by implementing rename and deletion. In fact this might be better, as one could control actions that would break project integrity, such as renaming the input file, and other actions - such as renaming a file referenced in the input - could be completed by changing all references as well.

**Comment by ajmay81** [comment]
Isn't `QFileDialog` effectively a file explorer by default? All the searches about this seem to be how to stop one being able to perform actions in a dialog, rather than allow them, eg. [here](https://www.appsloveworld.com/azure/121/preventing-file-actions-in-qfiledialog-such-as-copying-viewing-deleting-etc), so can't you just have an 'Explore project' item that just calls this?

It looks like there is [no standard way to launch a terminal on linux](https://unix.stackexchange.com/questions/91642/what-is-the-most-portable-method-of-launching-a-terminal-emulator). In my opinion it would be enough to have somewhere (maybe even the window titlebar) the full path to the project directory, anyone who knows how to use a terminal will know how to open one and change to that directory, anyone who doesn't probably shouldn't have an easy path to get there.

**Comment by pjknowles** [comment]
> Isn't `QFileDialog` effectively a file explorer by default? All the searches about this seem to be how to stop one being able to perform actions in a dialog, rather than allow them, eg. [here](https://www.appsloveworld.com/azure/121/preventing-file-actions-in-qfiledialog-such-as-copying-viewing-deleting-etc), so can't you just have an 'Explore project' item that just calls this?

Oh you are right. I had not realised, but it's true. So it would be completely pointless to write a delete or rename function that calls `QFileDialog` and then checks whether the deletion would be a good idea. Furthermore on macOS, the dialog offers in a file context menu the option to open in Finder; from there, there is a context menu to open a terminal.

So the summary is that the only thing that is needed is a `QFileDialog` with no following consequence. It's already there in the export menu item, but that would be non-obvious.

**Pull request merged**
